- block:
    - name: Ensure docker old versions are uninstalled
      ansible.builtin.apt:
        name:
          - docker.io
          - docker-doc
          - docker-compose
          - docker-compose-v2
          - podman-docker
          - containerd
          - runc
        state: absent

    - name: Ensure packages for adding GPG key are installed
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
        update_cache: true

    - name: Ensure keyrings dir exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "755"

    - name: Ensure Docker's official GPG key is added
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "644"

    - name: Set architecture variable
      ansible.builtin.command: dpkg --print-architecture
      register: architecture

    - name: Ensure docker repository is added
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ architecture.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

    - name: Ensure docker is installed
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        update_cache: true

    - name: Ensure docker is started and enabled on boot
      ansible.builtin.systemd_service:
        name: docker
        state: started
        enabled: true

    - name: Ensure users belong to docker group
      ansible.builtin.user:
        name: "{{ item }}"
        groups: docker
        append: true
      loop: "{{ docker_users }}"
  become: true
