- block:
    - name: Ensure dovecot.conf exists
      ansible.builtin.copy:
        src: "{{ project_path }}/.etc/dovecot/dovecot.conf"
        dest: /etc/dovecot/dovecot.conf
        owner: root
        group: root
        mode: "644"
      notify:
        - Restart dovecot

    - name: Ensure conf files in conf.d exist
      ansible.builtin.copy:
        src: "{{ project_path }}/.etc/dovecot/conf.d/{{ item }}"
        dest: /etc/dovecot/conf.d/{{ item }}
        owner: root
        group: root
        mode: "644"
      loop:
        - 10-auth.conf
        - 10-mail.conf
        - 10-master.conf
        - 10-ssl.conf
      notify:
        - Restart dovecot
  become: true
