- name: Ensure .git-credentials exists
  ansible.builtin.copy:
    src: /var/www/.secrets/git/.git-credentials
    dest: ~/.git-credentials
    mode: "400"
  become: true
  become_user: "{{ item.key }}"
