- block:
    - name: Ensure ssh key exists
      ansible.builtin.user:
        name: "{{ item.key }}"
        generate_ssh_key: true
        ssh_key_type: ed25519
        ssh_key_comment: "{{ item.value.ssh_key_comment }}"
        ssh_key_passphrase: "{{ item.value.ssh_key_passphrase }}"

    - name: Ensure authorized_keys exists
      ansible.builtin.copy:
        src: ~/.ssh/id_ed25519.pub
        dest: ~/.ssh/authorized_keys
        mode: "400"
        remote_src: true

    - name: Fetch id_ed25519
      ansible.builtin.fetch:
        src: ~/.ssh/id_ed25519
        dest: "{{ remote_path }}"

    - name: Fetch id_ed25519.pub
      ansible.builtin.fetch:
        src: ~/.ssh/id_ed25519.pub
        dest: "{{ remote_path }}"

    - name: Ensure id_ed25519 doesn't exist
      ansible.builtin.file:
        path: ~/.ssh/id_ed25519
        state: absent

    - name: Ensure id_ed25519.pub doesn't exist
      ansible.builtin.file:
        path: ~/.ssh/id_ed25519.pub
        state: absent
  become: true
  become_user: "{{ item.key }}"
