- name: Ensure secret dirs exists
  ansible.builtin.copy:
    src: "{{ project_path }}/.secrets/{{ item }}"
    dest: "{{ project_path }}/.secrets"
    owner: shbtnt
    group: shbtnt
    mode: "755"
  loop:
    - docker
    - git
    - lego
    - mysql
    - nginx
    - python
  become: true
