#!/bin/bash

date="$(date +%d)"

if [ -n "$1" ]; then
  if [[ "$1" =~ ^[1-9]$ ]]; then
    date="0$1"
  elif [[ "$1" =~ ^(0[1-9]|[12][0-9]|3[01])$ ]]; then
    date="$1"
  fi
fi

file_path="/var/log/sysstat/sa${date}"
sar -q -f $file_path | grep -E "[1-9][0-9]*\.[0-9]{2,}"
